// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_count_voxel_rays
List cpp_count_voxel_rays(NumericMatrix scandata, int numcols, int numheights, double xysize, double minxy, double maxxy, double zsize, double minz, double maxz, double maxdist, bool countReflected, Rcpp::Nullable<NumericMatrix> groundarg);
RcppExport SEXP _lidarvegdensity_cpp_count_voxel_rays(SEXP scandataSEXP, SEXP numcolsSEXP, SEXP numheightsSEXP, SEXP xysizeSEXP, SEXP minxySEXP, SEXP maxxySEXP, SEXP zsizeSEXP, SEXP minzSEXP, SEXP maxzSEXP, SEXP maxdistSEXP, SEXP countReflectedSEXP, SEXP groundargSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scandata(scandataSEXP);
    Rcpp::traits::input_parameter< int >::type numcols(numcolsSEXP);
    Rcpp::traits::input_parameter< int >::type numheights(numheightsSEXP);
    Rcpp::traits::input_parameter< double >::type xysize(xysizeSEXP);
    Rcpp::traits::input_parameter< double >::type minxy(minxySEXP);
    Rcpp::traits::input_parameter< double >::type maxxy(maxxySEXP);
    Rcpp::traits::input_parameter< double >::type zsize(zsizeSEXP);
    Rcpp::traits::input_parameter< double >::type minz(minzSEXP);
    Rcpp::traits::input_parameter< double >::type maxz(maxzSEXP);
    Rcpp::traits::input_parameter< double >::type maxdist(maxdistSEXP);
    Rcpp::traits::input_parameter< bool >::type countReflected(countReflectedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<NumericMatrix> >::type groundarg(groundargSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_count_voxel_rays(scandata, numcols, numheights, xysize, minxy, maxxy, zsize, minz, maxz, maxdist, countReflected, groundarg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lidarvegdensity_cpp_count_voxel_rays", (DL_FUNC) &_lidarvegdensity_cpp_count_voxel_rays, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_lidarvegdensity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
