// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rays_in_voxels
NumericVector rays_in_voxels(NumericMatrix scandata, int numcols, int numheights, double xysize, double minxy, double maxxy, double zsize, double minz, double maxz, double maxdist);
RcppExport SEXP _lidarvoxel_rays_in_voxels(SEXP scandataSEXP, SEXP numcolsSEXP, SEXP numheightsSEXP, SEXP xysizeSEXP, SEXP minxySEXP, SEXP maxxySEXP, SEXP zsizeSEXP, SEXP minzSEXP, SEXP maxzSEXP, SEXP maxdistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scandata(scandataSEXP);
    Rcpp::traits::input_parameter< int >::type numcols(numcolsSEXP);
    Rcpp::traits::input_parameter< int >::type numheights(numheightsSEXP);
    Rcpp::traits::input_parameter< double >::type xysize(xysizeSEXP);
    Rcpp::traits::input_parameter< double >::type minxy(minxySEXP);
    Rcpp::traits::input_parameter< double >::type maxxy(maxxySEXP);
    Rcpp::traits::input_parameter< double >::type zsize(zsizeSEXP);
    Rcpp::traits::input_parameter< double >::type minz(minzSEXP);
    Rcpp::traits::input_parameter< double >::type maxz(maxzSEXP);
    Rcpp::traits::input_parameter< double >::type maxdist(maxdistSEXP);
    rcpp_result_gen = Rcpp::wrap(rays_in_voxels(scandata, numcols, numheights, xysize, minxy, maxxy, zsize, minz, maxz, maxdist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lidarvoxel_rays_in_voxels", (DL_FUNC) &_lidarvoxel_rays_in_voxels, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_lidarvoxel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
