# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_count_voxel_rays <- function(scandata, numcols, numheights, xysize, minxy, maxxy, zsize, minz, maxz, maxdist, countReflected = FALSE, groundarg = NULL) {
    .Call(`_lidarvegdensity_cpp_count_voxel_rays`, scandata, numcols, numheights, xysize, minxy, maxxy, zsize, minz, maxz, maxdist, countReflected, groundarg)
}

